### ISSUE TITLE
input field value to output slot

### ISSUE THREAD

**Issue by spranger** [iCubbles/basic-html-components#1]
in IE11 the input field value is not propagated to the output slot when you press ENTER in input field.
you first have to click outside or leave input field to get value

**Comment by hrbu** [comment]
@edwingamboa Please would you try to fix this and release a new version into the cubbles.world/shared store.

As I realised right now, within the cubbles.world the webpackage is called "...`basic-html-components`" - but the github repo is called "`base-html-components`". Think it would be a good idea to use the same name for the repo and the webpackage (i would prefer to rename the repository on github).

**Comment by edwingamboa** [comment]
The issue is already solved. You can use the 0.1.1 version of the `basic-html-components`. You can check this [example](https://cubbles.world/shared/com.incowia.basic-html-components@0.1.1/cubx-input/demo/index.html).
